---
title: "Estimating Complex Discrete Choice Models by MACML"
author: "Sidharthan Raghu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```{r setup}
library(dplyr)

```

# MACML


# Model

The `cs_uncorrelated` dataset is included in the `macml` package. 

```{r setup_data}
dt <- tbl_df(cs_uncorrelated)
nobs <- 5000
nvar <- 5 
nc <- 5		
```

The dataset contains measurements on five attributes of five alternatives.

```{r attribute}
dtaX <- as.matrix(dt %>% select(x01:x25))
dtaCh <- as.matrix(dt %>% select(f1:f5))
dtaChNum <- apply(dtaCh, 1, function(x) which(x == 1))
```


```{r appdel}
appdel <- kronecker(matrix(1, 1, nc - 1), dtaCh)
appdel_tplt <-  matrix(nrow = 0, ncol = nc * (nc - 1))
for(inc in 1:nc) {
  appdel_tplt_row = matrix(nrow=1,ncol=0)
  for(jnc in 1:nc) {
    if(jnc != inc) {
      temp <- matrix(0, nrow = 1, ncol = nc)
      temp[1, jnc] <- 1
      appdel_tplt_row <- cbind(appdel_tplt_row, temp)
    }
  }
  appdel_tplt = rbind(appdel_tplt,appdel_tplt_row);
}

appdel1 <- appdel_tplt[dtaChNum, ]
appdel <- t(appdel)
appdel1 <- t(appdel1)
appdiff <- appdel -  appdel1
```  

```{r dontknow}
ID <- 0.5 * diag(nc - 1) + 0.5 * matrix(1, nrow = nc - 1, ncol = nc - 1)
outProd <- 0  
finalIter <- 0
bInit <- c(0,0,0,0,0,1,1,1,1,1)
seed10 <- 10000
```

```{r first_model}
finalIter <- 0 
res1 <- optim(bInit, lpr, lgd, method="BFGS", 
              control = list(maxit = 100, trace = 3, fnscale = -1, REPORT = 1),
              hessian = TRUE)
print(res1)
finalIter <- 1
```

```{r second_model}
res2 <- optim(res1$par, lpr, lgd, method="BFGS", 
              control = list(maxit=1, trace=3, fnscale=-1, REPORT=1))
print(res2)
```

```{r}
cov2 <- solve(res1$hessian) %*% outProd %*% solve(res1$hessian) / nobs / nobs

estimate <- res1$par
stdErr <- sqrt(diag(cov2))

print(cbind(estimate,stdErr))
```


